eureka:
  server:
    enable-self-preservation: false # 네트워크 장애시 등록된 모든 서비스가 해제되는 것을 방지 개발에서는 false, 운영에선 true
  instance:
    hostname: ${HOSTNAME}.eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_servers:http://localhost:8761/eureka}